name: SkillifyCore
version: '1.0.16'
main: me.zaksen.skillify_core.SkillifyCore
api-version: '1.20'
authors: [ Zaksen_ ]
commands:
  custom_items:
    description: Open items menu or give item
    usage: /<command> <subcommand>
    aliases:
      - c_items
      - customitems
      - citems
  skillify_reload:
    description: Reload core and some sub plugins logic
    usage: /<command>
    aliases:
      - slfy_reload
      - slfy_r